version: 0.0
os: linux
files:
  - source: / 
    destination: /
hooks:
BeforeInstall:
  - location: whiz/install_dependencies.sh
    timeout: 300
    runas: root
AfterInstall:
  - location: whiz/install_nginx.sh
    timeout: 300
    runas: root
ApplicationStop:
  - location: whiz/stop_nginx.sh
    timeout: 300
    runas: root    
ApplicationStart:
  - location: whiz/start_nginx.sh
    timeout: 300
    runas: root
